spring:
  data:
    mongodb:
      database: SpringBootDB
      auto-index-creation: true
      uri: mongodb+srv://knightkrish:rmtDzoQ5nk7aCwX9@cluster0.jepfx.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0spring.data.mongodb.auto-index-creation=true
      authentication-database: admin
      host: localhost
      port: 27017

  security:
    user:
      name: kd
      password: kd

server:
  port: 8000